# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Super Duper' do

pod 'Parse', '1.6'
pod 'GoogleAnalytics'
pod 'Pinterest-iOS'

end

target 'Super DuperTests' do

end

